# Preliminary Research Notes 

# Notes on the project 

# Rsearch Question 

RQ:

# Potential Research Papers to read to get started

Potocki, R. (2011). Belarus: A tale of two elections. Journal of Democracy, 22(3), 49-63.

Silitski, V. (2005). Preempting democracy: The case of Belarus. Journal of Democracy, 16(4), 83-97.

Frear, M. (2014). The parliamentary elections in Belarus, September 2012. Electoral Studies, 33(1), 350-353.

Li, R. (2014). The influence of geospatial factors on democracy: Its representation on web interface design. Journal of the Association for Information Science and Technology, 65(2), 313-333.

Min, B. (2008, April). Democracy and light: electoral accountability and the provision of public goods. In annual meeting of the Midwest Political Science Association.

Zahorski, A. (2020). Multilevel regression with poststratification for the national level Viber/Street poll on the 2020 presidential election in Belarus. arXiv preprint arXiv:2009.06615.

Ubarevičienė, R., Burneika, D., & van Ham, M. (2012). Socio-spatial transformations, suburbanisation, and voting behaviour in the Vilnius urban region.
